name: Tests and Linting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
    - run: npm install
    - run: npm run lint
    - run: npm test
      env:
        CI: true
